#config:
#  version-candidate: VERSION
#  dependencies:
#    dependencies: [build]
#    typedb-client-java: [release]
#
#build:
#  quality:
#    filter:
#      owner: vaticle
#      branch: master
#    dependency-analysis:
#      image: vaticle-ubuntu-21.04
#      command: |
#        bazel run @vaticle_dependencies//factory/analysis:dependency-analysis
#  correctness:
#    release-development:
#      filter:
#        owner: vaticle
#        branch: development
#      image: vaticle-ubuntu-21.04
#      type: foreground
      # TODO: implement this
      # dependencies: [build, test-query-typeql-lang, test-query-typeql-java, test-example-java, test-example-nodejs, test-example-python, test-links]
#      command: |
#        export ARTIFACT_USERNAME=$REPO_VATICLE_USERNAME
#        export ARTIFACT_PASSWORD=$REPO_VATICLE_PASSWORD
#        bazel run @vaticle_dependencies//distribution/artifact:create-netrc
#        export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME
#        export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL
#        export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN
#        bazel run @vaticle_dependencies//tool/release:docs -- $FACTORY_OWNER web-docs development $FACTORY_REPO pages/docs $FACTORY_COMMIT
#    release-staging:
#      filter:
#        owner: vaticle
#        branch: master
#      image: vaticle-ubuntu-21.04
#      type: foreground
      # TODO: implement this
      # dependencies: [build, test-query-typeql-lang, test-query-typeql-java, test-example-java, test-example-nodejs, test-example-python, test-links]
#      command: |
#        export ARTIFACT_USERNAME=$REPO_VATICLE_USERNAME
#        export ARTIFACT_PASSWORD=$REPO_VATICLE_PASSWORD
#        bazel run @vaticle_dependencies//distribution/artifact:create-netrc
#        export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME
#        export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL
#        export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN
#        bazel run @vaticle_dependencies//tool/release:docs -- $FACTORY_OWNER web-docs master $FACTORY_REPO pages/docs $FACTORY_COMMIT
#  execution:
#    - release-development
#    - release-staging
